Keep a log of the import/export tools
wpwhitesecurity/activity-log-gravity-forms pull request #73
Opened 2022-02-17 18:57 UTC by DannyWPWS

Fixes #71

2022-02-18 07:10 UTC, martinkrcho commented on includes/wsal-functions.php
> +	$should_load = ( $default || ! empty( $frontend_events['gravityforms'] ) ) ? true : false;
This could be simplified like this:
```suggestion
	return ( $default || ! empty( $frontend_events['gravityforms'] );
```

2022-02-18 07:14 UTC, martinkrcho commented on includes/wsal-functions.php
> + * Checks for exporing of form data and triggers an event if needed. We do this here has the sensor does not detect this change.
```suggestion
 * Checks for exporing of form data and triggers an event if needed. We do this here as the sensor does not detect this change.
```

2022-02-18 07:26 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			$alert_code = 5719;
The following lines can be moved BEFORE the `foreach` loop. The change will slightly improve the performance.
```
$alert_code = 5719;
$wsal = WpSecurityAuditLog::GetInstance();

if ( ! isset( $wsal->alerts ) ) {
	$wsal->alerts = new WSAL_AlertManager( $wsal );
}
```
I would also consider not using variable `$alert_code` as it doesn't change within the scope of the function under any circumstances.

2022-02-18 07:29 UTC, martinkrcho requested changes
Changes overall seem OK to me. I like all the coding standards improvements 👍🏼 

I left some suggestions for improvement.

Also, can you please make sure all the code complies with the WordPress coding standards while you're at it? There are some functions missing phpdocs completely and others having just some partial documentation that fails phpcs validation.

2022-02-18 15:04 UTC, DannyWPWS commented
Done :) WIll revisit the others now also

2022-02-21 07:13 UTC, martinkrcho commented on activity-log-gravity-forms.php
>   * @subpackage Wsal Custom Events Loader
Package names cannot contain spaces. Please fix it here.
https://pear.php.net/package/PhpDocumentor/docs/latest/phpDocumentor/tutorial_tags.package.pkg.html
> PACKAGES MUST BE ONE WORD WITH NO SPACES OR NEWLINES CONTAINING ONLY LETTERS, DIGITS, and "_", "-", "[" or "]"

How about we use `wsal` for the `@package` and `wsal-gravity-forms` for `@subpackage`?

2022-02-21 07:14 UTC, martinkrcho commented on includes/wsal-functions.php
> + * Checks for exporing of form data and triggers an event if needed. We do this here as the sensor does not detect this change.
```suggestion
 * Checks for exporting of form data and triggers an event if needed. We do this here as the sensor does not detect this change.
```

2022-02-21 07:16 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
>   * Custom Sensors for PLUGINNAME
```suggestion
 * Custom Sensors for Gravity Forms plugin.
```

2022-02-21 07:17 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			add_action( 'wp_ajax_gf_process_export', array( $this, 'event_process_export' ), 10, 1 );
```suggestion
			add_action( 'wp_ajax_wsal_gf_process_export', array( $this, 'event_process_export' ), 10, 1 );
```

2022-02-21 07:18 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			$wsal = WpSecurityAuditLog::GetInstance();
The following code can be moved before the `foreach` loop to improve performance.
```
$wsal = WpSecurityAuditLog::GetInstance();
if ( ! isset( $wsal->alerts ) ) {
	$wsal->alerts = new WSAL_AlertManager( $wsal );
}
```

2022-02-21 07:19 UTC, martinkrcho requested changes
Looking much better, @DannyWPWS .

I found couple of small areas for improvement again. Sorry to be picky, but let's take it one step further since we're already updating the extension :)

2022-02-21 14:42 UTC, DannyWPWS commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			add_action( 'wp_ajax_gf_process_export', array( $this, 'event_process_export' ), 10, 1 );
Im not sure on this one, as im using "wp_ajax_gf_process_expor" to detect an export

2022-02-21 17:57 UTC, DannyWPWS commented
This PR also fixes #74

2022-02-22 07:33 UTC, martinkrcho commented on wp-security-audit-log/custom-alerts.php
> +				esc_html__( 'An entry was created edited', 'wsal-gravity-forms' ),
Created or edited?

Should this be actually like the following?
```suggestion
				esc_html__( 'An entry was edited', 'wsal-gravity-forms' ),
```

2022-02-22 07:37 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			if ( ! empty( rgar( $entry, '1' ) ) ) {
Function `rgar` is called twice for each of values 1, 2 and 3. Can you please change this part to use a `for` loop and only call `rgar` once in each run?

Should we translate the default value `Not found`?

2022-02-22 07:38 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +		if ( ! isset( $wsal->alerts ) ) {
`$wsal` variable is not available at this point. It seems you forgot to move it along with the `$wsal->alerts` instantiation.

2022-02-22 07:46 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			add_action( 'wp_ajax_gf_process_export', array( $this, 'event_process_export' ), 10, 1 );
That sounds a bit risky. What happens if the export is stopped inside Gravity Forms' AJAX handler function?

Can we use action `gform_post_export_entries` instead?
https://github.com/pronamic/gravityforms/blob/main/export.php#L946

```
/**
 * Fires after exporting all the entries in form
 *
 * @since 2.4.5.11 Added the $export_id param.
 * @since 1.9.3
 *
 * @param array  $form       The Form object to get the entries from
 * @param string $start_date The start date for when the export of entries should take place
 * @param string $end_date   The end date for when the export of entries should stop
 * @param array  $fields     The specified fields where the entries should be exported from
 * @param string $export_id  A unique ID for the export.
 */
do_action( 'gform_post_export_entries', $form, $start_date, $end_date, $fields, $export_id );
```

2022-02-22 07:50 UTC, martinkrcho requested changes
I left couple of comments - things that can be improved in terms of performance and reliability.

2022-02-22 12:13 UTC, DannyWPWS commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			add_action( 'wp_ajax_gf_process_export', array( $this, 'event_process_export' ), 10, 1 );
Annoyingly, no - it just doesn't fire when exporting the forms themselves.

I was surprised too but in GF they have a function running all the time (on init) "maybe_export" which looks for the same thing/referrer we do and nothing else I can use is fired along the way. I was quite surprised by how they handle it tbh

2022-02-22 13:02 UTC, DannyWPWS commented on wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php
> +			add_action( 'wp_ajax_gf_process_export', array( $this, 'event_process_export' ), 10, 1 );
Ok I was confused and it WAS the entries this filter was referring too - sorry about that!

2022-02-23 09:41 UTC, martinkrcho approved these changes
Huge step in the right direction 👍🏼  All seems to look OK now.

2022-02-23 09:41 UTC, merged